# Generated by Django 4.1.7 on 2023-02-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_remove_registered_user_ip_address_attack_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack_action',
            name='buff',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='attack_action',
            name='equipment',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='attack_action',
            name='shark',
            field=models.CharField(max_length=30),
        ),
    ]
